### ISSUE TITLE
Компонента для FreePBX 14

### ISSUE THREAD

**Issue by poteh** [shachneff/BROM-Asterisk-Native#12]
Добрый день, коллеги.
Кто-нибудь запускал эту компоненту для работы с FreePBX 14 версии? Подключиться и сделать звонок у меня получилось, но вот Events не валятся и всё тут. С 2 версией FreePBX проблем нет. Неужели что то поменялось в AMI в новой версии?

**Comment by shachneff** [comment]
Поделитесь, пожалуйста, результатом изысканий! 
Мне предстоит эта же задача на свежем FreePBX Distro в ближайшие дни.
До этого я работал только с чистым Asterisk

**Comment by poteh** [comment]
На самом деле всё работает, проблема была в моей невнимательности и замыленном взгляде.
Тестировал одновременно эту библиотеку и Asterisk.Net.dll. 
Сначала пробовал библиотеку Asterisk.Net.dll. Тестирование проводил удаленно на сервере предприятия, прав админа там у меня нет, устанавливал местный админ (библиотека работает через СОМ).
Подключился к AMI успешно, звонок совершил, но события не приходят. Перерыл всё что можно было - ничего не нашёл почему не приходят события.
Параллельно пробовал использовать эту библиотеку, также подключился, звонок совершил, события не валятся.
Спустя несколько дней свежим взглядом начал поэтапно анализировать происходящее в системе. Выяснилось, что библиотека Asterisk.Net.dll криво зарегистрировалась в системе, после перерегистрации события начали валиться. А в этой библиотеке были применены регулярные выражения, которые не совпадали с моими события, поэтому была тишина на входе.
В итоге остановился на этой библиотеке.
Касаемо использования, сейчас расковыриваю Freepbx, т.к. входящая маршрутизация построена на RingGroups, ищу способ как быстро и однозначно получить номера extensions на которые поступает входящий вызов. В событиях которые валятся сейчас, на мой взгляд, реализовано не совсем очевидно и слишком поздно. Хотя может я и не прав.

**Comment by hellslade** [comment]
Привет! Не могли бы вы скинуть скомпилированную DLL на почту alex@youbp.ru ?

**Comment by shachneff** [comment]
Тема закрыта. Создавайте новую актуальную тему если надо.
