### ISSUE TITLE
Поправлена кодировка

### ISSUE THREAD

**Issue by derectiva** [shachneff/BROM-Asterisk-Native#13]
Поправили кодировку в файле AddInNative.cpp
В архиве скомпилированная dll и файл AddInNative.cpp

**Comment by derectiva** [comment]
[BROM-Asterisk-Native-master.zip](https://github.com/shachneff/BROM-Asterisk-Native/files/3271845/BROM-Asterisk-Native-master.zip)

**Comment by Severbap** [comment]
Что-то у мне она не хочет подключатся, установка проходит успешно. Но вот дальше подключение вываливается в ложь.
Компоненту брал что была выложена тут.
Манифесте прописал: 
`<?xml version="1.0" encoding="UTF-8" ?> 
<bundle xmlns="http://v8.1c.ru/8.2/addin/bundle"> 
	<component os="Windows" path="BROM-Asterisk-Native.dll" type="native" arch="i386"/>
</bundle>
`
Поместил в zip кинул в макет обработки с именем "BROMAsteriskNative"
Прописал код 1С для теста: 
`	ОчиститьСообщения();
	
	СисИнфо = Новый СистемнаяИнформация;
	Сообщить(СисИнфо.ТипПлатформы);
	
	АдресВоВременноеХранилище = ПоместитьВоВременноеХранилище(ПолучитьМакет("BROMAsteriskNative"));
	
	Результат = ПодключитьВнешнююКомпоненту(АдресВоВременноеХранилище, "Test", ТипВнешнейКомпоненты.Native);
	Если Результат Тогда 
		
		Попытка
			
			ОбъектКомпоненты = Новый("AddIn.Test.ROM-Asterisk-Native");
			Сообщить("Успешное создание Компоненты");
			
		Исключение
			
			РезультатОшибка = ОписаниеОшибки();
			Сообщить(РезультатОшибка);
			
		КонецПопытки;
		
	Иначе 
		
		УстановитьВнешнююКомпоненту(АдресВоВременноеХранилище);
		
		Результат = ПодключитьВнешнююКомпоненту(АдресВоВременноеХранилище, "Test", ТипВнешнейКомпоненты.Native);
		
		Если Результат Тогда 
			
			Попытка
				ОбъектКомпоненты = Новый("AddIn.Test.ROM-Asterisk-Native");
				Сообщить("Успешное создание Компоненты");
			Исключение
				
				РезультатОшибка = ОписаниеОшибки();
				Сообщить(РезультатОшибка);
				
			КонецПопытки;
			
		Иначе 
			
			Сообщить("Подключение компоненты не выполнено!");
			
		КонецЕсли;	
		
	КонецЕсли;	
`
Как-то странно все.

**Comment by Severbap** [comment]
Тоже самое и на клиента 64 "Подключение компоненты не выполнено"
`<?xml version="1.0" encoding="UTF-8" ?> 
<bundle xmlns="http://v8.1c.ru/8.2/addin/bundle"> 
	<component os="Windows" path="BROM-Asterisk-Native.dll" type="native" arch="x86_64"/>
</bundle>`

**Comment by derectiva** [comment]
В понедельник скину решение. Dll не подкидывали в клиент,  ее загрузили в конфигурацию. Подробностей не знаю,  делал программист.

**Comment by Severbap** [comment]
Хорошо

**Comment by derectiva** [comment]
База в приложении.  При первом запуске нужно установить в константах параметры подключения к ami и у пользователя установить внутренний номер телефона который будем ловить(галочка "Использовать телефонию" обязательна). После установки всех параметров перезапустить клиент 1с. Тестировал на Asterisk 13.
[asterisk_brom.zip](https://github.com/shachneff/BROM-Asterisk-Native/files/3271055/asterisk_brom.zip)

**Comment by Severbap** [comment]
![image](https://user-images.githubusercontent.com/51443868/59179277-35fbcf00-8b6a-11e9-83d7-18a94e211ab8.png)
Облом что-то вообще не хочет

**Comment by Severbap** [comment]
Это конфигурация которая скачена и запущена по ссылке.

**Comment by derectiva** [comment]
Установить и перезагрузить ПК
https://www.microsoft.com/ru-ru/download/details.aspx?id=48145

**Comment by Severbap** [comment]
Тоже самое, пробовал на разных ПК

**Comment by shachneff** [comment]
Сообщите версию и разрядность платформы

**Comment by derectiva** [comment]
а платформа у вас какая?

**Comment by Severbap** [comment]
![image](https://user-images.githubusercontent.com/51443868/59185826-1371b200-8b7a-11e9-8ec0-c547ebad5611.png)
Пробовал на разных

**Comment by shachneff** [comment]
8.3.13.1809 - это, если я не ошибаюсь, версия, в которой 1С изменила защиту и разделила программно ПРОФ и КОРП функциональность.

Чисто для эксперимента попробуйте более ранний релиз.

**Comment by Severbap** [comment]
![image](https://user-images.githubusercontent.com/51443868/59186210-fb4e6280-8b7a-11e9-96d9-74c0a77697ce.png)

тот же

**Comment by derectiva** [comment]
Сейчас протестирую на новом пк, может visual studio что то регистрирует в системе

**Comment by Severbap** [comment]
[Обработка для тестирования компоненты Брома.zip](https://github.com/shachneff/BROM-Asterisk-Native/files/3271485/default.zip)
В этой обработке ставится, но подключение не происходит.

**Comment by derectiva** [comment]
msvcp140d.dll именно это он требует, а как оказалось это отладочная библиотека для visual studio
Пересобрал библиотеку. В приложении новая dll и dt
[ast.zip](https://github.com/shachneff/BROM-Asterisk-Native/files/3271544/ast.zip)

**Comment by derectiva** [comment]
работает на новом ПК без доп установок. Установленной visual c++ 2015, которая идет в комплекте с 1с, достаточно для загрузки dll

**Comment by Severbap** [comment]
[Обработка для тестирования компоненты Брома.zip](https://github.com/shachneff/BROM-Asterisk-Native/files/3271613/default.zip)
Тут вроде завелась 64-разрядная, компонента для 32-х отдельно - есть ссылка?

**Comment by Severbap** [comment]
![image](https://user-images.githubusercontent.com/51443868/59189516-e544a000-8b82-11e9-9a46-e2073a5c558c.png)
Вроде пошло с тем же архивом который в обработке

**Comment by derectiva** [comment]
Работает и на более новых версиях
![Clip2net_190610142815](https://user-images.githubusercontent.com/45368463/59192711-0493fb00-8b8c-11e9-9706-dbf6a2ed29ef.png)

**Comment by Severbap** [comment]
Я тоже проверил, все успешно.

**Comment by derectiva** [comment]
Тогда закрываю задачу
