### ISSUE TITLE
Не собирается под VS2015

### ISSUE THREAD

**Issue by 23W** [shachneff/BROM-Asterisk-Native#2]
Есть ошибки в объявлении заголовков под Window платформой.
Правильно stdafx.h должен выглядеть так:
```
#ifndef __STDAFX_H__
#define __STDAFX_H__

#ifdef _WINDOWS
#include <Winsock2.h>
#include <ws2tcpip.h>
#include <process.h>
#include <Windows.h>
#endif //_WINDOWS

#if defined(__linux__) || defined(__APPLE__)
#define LINUX_OR_MACOS
#endif

#endif //__STDAFX_H__
```

Заголовок AddInNative.cpp так:
```
#include "stdafx.h"

#ifdef __linux__
#include <unistd.h>
#include <stdlib.h>
#include <signal.h>
#endif

#include <wchar.h>
#include <stdio.h>
#include <string>
#include <array>
#include <vector>
#include <regex>

#include "AddInNative.h"

#pragma comment(lib, "Ws2_32.lib")
```

Смысл такой: `<Winsock2.h>` и `<ws2tcpip.h>` нужно подключать ДО `<Windows.h>`, а `<vector>`, `<regex>` и другой STL - ДО `"AddInNative.h"`, т.к. иначе `Winsock2.h` переопределяет некоторые структуры из `Windows.h`, а в `AddInNative.h` используются векторы и строки, объявленные после подключения `AddInNative.h` и в результате - ошибки.

**Comment by shachneff** [comment]
Спасибо! Да, теперь без ошибок собирается!

**Comment by 23W** [comment]
рад что смог помочь :)
