### ISSUE TITLE
Убрать из кода демо-режим, привязку к компу

### ISSUE THREAD

**Issue by shachneff** [shachneff/BROM-Asterisk-Native#4]
Убрать из кода демо-режим, привязку к компу - это открытая компонента, они тут не нужны.

**Comment by SimolSem** [comment]
Да, "демо" заменяет на звездочки после 100-го сообщения. Убрать не сложно, но нада студиа.
Пока после 99 сообщения переподключаюсь.

**Comment by korv1982** [comment]
Демо режим был сделан для разработчиков которые хотят продавать компоненту. Защита абы что но ее достаточно. Сама процедура прописана в открытом коде. можно на базе нее создать сайт с лицензированием. Все последние исправления вносил я. Добавил в pull request. Всегда будет недемо

**Comment by shachneff** [comment]
Тема закрыта. Создавайте новую актуальную тему если надо.
