### ISSUE TITLE
Непорядок с кодировкой файла

### ISSUE THREAD

**Issue by shachneff** [shachneff/BROM-Asterisk-Native#6]
Если кодировка cpp-файла - Юникод, то свойства ВК в 1С - кракозяблы.
Если кодировку изменить на Windows 1251 - в 1С все норм, но в Студии и в git - кириллица кракозяблами

**Comment by vadim-ver** [comment]
Использую VS2015 Community, кодировка файлов cpp - win1251, в Студии - все нормально

**Comment by shachneff** [comment]
Тема закрыта. Создавайте новую актуальную тему если надо.
