### ISSUE TITLE
УстановитьРегулярноеВыражение не работает "Newchannel.{1,}|Bridge.{1,}"

### ISSUE THREAD

**Issue by shachneff** [shachneff/BROM-Asterisk-Native#7]
SimolSem commented 5 minutes ago
Завтра буду разбирать УстановитьРегулярноеВыражение
не работает "Newchannel.{1,}|Bridge.{1,}"

**Comment by SimolSem** [comment]
"Newchannel|Bridge" работает, сейчас посмотрю про точку

**Comment by korv1982** [comment]
Вот такой вариант работает 
"BridgeEnter([^.]*)CallerIDNum: "+"999"+"|BridgeLeave([^.]*)CallerIDNum: "+"999"+"|MIXMONITOR_FILENAME|Disconnected"

**Comment by hellslade** [comment]
Ребят, не работают регулярки. И так и эдак пишу, события вообще не приходят.
Если делают УстановитьРегулярноеВыражение("150") -- внутренний номер, то вроде как работает, события приходят все, где есть такая строка.
Если пишут что-то сложнее, например так "DialBegin.{1,}?150" или так "DialBegin.*?150", то события перестают приходить вообще. Писал даже просто такую регулярку "DialBegin", тоже не работает.
Asterisk 13

Пример события DialBegin
`Event: DialBegin
Privilege: call,all
Channel: SIP/T72-00000012
ChannelState: 6
ChannelStateDesc: Up
CallerIDNum: 89*******17
CallerIDName: 89*******17
ConnectedLineNum: 150
ConnectedLineName: ***
Language: ru
AccountCode: 
Context: macro-dial-one
Exten: s
Priority: 55
Uniqueid: 1568287827.47
Linkedid: 1568287827.47
DestChannel: PJSIP/150-00000011
DestChannelState: 0
DestChannelStateDesc: Down
DestCallerIDNum: 150
DestCallerIDName: ***
DestConnectedLineNum: 89*******17
DestConnectedLineName: 89*******17
DestLanguage: ru
DestAccountCode: 
DestContext: func-apply-sipheaders
DestExten: s
DestPriority: 14
DestUniqueid: 1568287836.48
DestLinkedid: 1568287827.47
DialString: 150/sip:150@192.168.1.7:5060`

Фильтр стоит такой "dialplan,call,agent,command".

В чем проблема может быть? В компоненте или я что-то не так делаю?
Регулярки проверял тут https://www.debuggex.com

**Comment by hellslade** [comment]
Наврал немного. Просто "DialBegin" работает (это просто у меня астериск упал). Но "DialBegin.{1,}?150" уже не работает. Такое ощущение, что в регэкспах флаг s (точка соответствует переводу строки) не включен.

**Comment by korv1982** [comment]
> Наврал немного. Просто "DialBegin" работает (это просто у меня астериск упал). Но "DialBegin.{1,}?150" уже не работает. Такое ощущение, что в регэкспах флаг s (точка соответствует переводу строки) не включен.

Не включен. 
Попробуй DialBegin(.*?(\n))+.*?ConnectedLineNum: 150

**Comment by hellslade** [comment]
> Не включен.
> Попробуй DialBegin(._?(\n))+._?ConnectedLineNum: 150

Результат тот же. А нельзя добавить этот флаг? Хотя я погуглил и вообще такого флага в С не нашел ((. Или может быть перед regex_seach из Data удалить все переносы строк предварительно?

У вас самих то как регулярки настроены? )

**Comment by korv1982** [comment]
Тогда попробуй еще вот так
DialBegin(.*(\n))*(.*ConnectedLineNum: 150)

**Comment by korv1982** [comment]
Сжирает символы:
`DialBegin(.*(\n))*(.*ConnectedLineNum: 150)`

**Comment by hellslade** [comment]
Сделал так, событие прилетело "DialBegin(.*?(\n|\r))+.?ConnectedLineNum: 150"
Но это какой-то мазохизм :)

Спасибо за помощь!

**Comment by korv1982** [comment]
Вообще более правильно было бы так. `DialBegin(.*[(\n)|\r\n])*(.*ConnectedLineNum: 150)`
Т.к. в Windows перевод строки это \r\n а в Linux \n

**DialBegin** соответствует символам DialBegin буквально (с учетом регистра)

**1-я группа** ` (. * [(\n) | \r\ n]) *`

`.*` - соответствует любому символу кроме перевода строки. 
`[\n|\r\n]` - соответствует переводу строки `\n` или `\r\n`
Все это обернуто в `()*` соответствует группе с множителем `*`, т.е. неограниченное количество раз до.
**2-я группа** `(.* ConnectedLineNum: 150)`
`.*` соответственно любые символы до ConnectedLineNum: 150. 
2ю группу можно было бы и по другому написать. например `(.*LineNum: 150)`

Везде учитывается регистр

**Comment by hellslade** [comment]
> Вообще более правильно было бы так. `DialBegin(.*[(\n)|\r\n])*(.*ConnectedLineNum: 150)`

Да, так лучше, спасибо, все получилось!

**Comment by shachneff** [comment]
Тема закрыта. Создавайте новую актуальную тему если надо.
