### ISSUE TITLE
AppVeyor

### ISSUE THREAD

**Issue by ghost** [shachneff/BROM-Asterisk-Native#8]
нужно собирать с помощью AppVeyor

тогда 

* можно автоматически публиковать dll на GitHub Release
* станет понятно - как собрать самому

еще бы travis.ci - чтобы понять что работает на *.nix (если работает ;-))

со своей стороны могу помочь в настройке, а также в упаковке в zip для прямого подключения в виде макета

**Comment by shachneff** [comment]
Тема закрыта. Создавайте новую актуальную тему если надо.
